#!/usr/bin/env python3
"""Render the corpus guard campaign report (funnel-first, disclosures included)
from the driver's JSONL + summary. Deterministic: same inputs, same MD.

Usage: python3 scripts/corpus_campaign_report.py \
           --results eval/campaigns/local_results_2026-07.jsonl \
           --out eval/campaigns/2026-07-guard-campaign.md
"""
from __future__ import annotations

import argparse
import json
import subprocess
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DISCLOSURES = """\
## Disclosures (read before quoting any number)

- **Traffic provenance**: every execution is a real n8n engine run through a
  production webhook, but the INPUTS are controlled payloads generated by the
  campaign driver (varied values, never varied schema on the valid side). This is
  benchmark texture over real community-authored workflow logic — it is NOT
  customer traffic and must never be described as such.
- **Trigger re-attachment**: the mining harness had neutered every corpus workflow
  to a manual trigger; the campaign re-attached a webhook trigger (same node name,
  business logic byte-identical — see scripts/corpus_campaign_prepare.py). All
  other nodes, connections, and whitelisted settings are unmodified.
- **The 17 "wild" workflows** from the recall validation have no committed
  artifacts (third-party PII) and are excluded. The claim ceiling is the committed
  corpus of 70.
- **error_route non-recurrence is partly structural**: once settings.errorWorkflow
  is configured and resolvable, the error_workflow detector clears by
  construction. The evidential weight for that lane sits on the delivered-route
  probe and (where achievable) the 30-success accumulation, not on non-recurrence.
- **No outcome was concluded by a script.** Cases stop at ready-for-review; only a
  human concludes `prevented`, per case, after reviewing the evidence.
- **Rejected-probe side effects**: malformed probes fired at installed guards
  produce real failed executions that legitimately fire `n8n_node_error` /
  `n8n_missing_error_workflow` detections (disclosed dashboard noise; proven not
  to constitute recurrence for the guarded fingerprint).
- **Tier-A/live selection is biased by construction**: live-subset workflows are
  picked from those that fully verified locally. The funnel below is the
  unbiased view; the live subset is a showcase of the verified end of it.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--title", default="Corpus guard campaign — 2026-07")
    args = parser.parse_args()

    rows = [json.loads(line) for line in Path(args.results).read_text().splitlines()]
    summary_path = Path(args.results).with_suffix(".summary.json")
    summary = json.loads(summary_path.read_text()) if summary_path.exists() else {}

    stages = Counter(r.get("stage") for r in rows)
    lanes = Counter(str(r.get("lane")) for r in rows)
    excl = Counter(r.get("lane_reason") for r in rows if r.get("stage") == "excluded")
    applied = [r for r in rows if r.get("stage") in ("applied", "probed", "ready")]
    probed = [r for r in rows if r.get("stage") in ("probed", "ready")]
    ready = [r for r in rows if r.get("ready_for_outcome_review")]
    standing = [r for r in probed
                if "standing durable guard" in str(r.get("successes_note", ""))]

    corpus_sha = subprocess.run(
        ["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
        capture_output=True, text=True).stdout.strip()

    lines: list[str] = []
    a = lines.append
    a(f"# {args.title}")
    a("")
    a("Real guard lifecycles across the committed community-workflow corpus, run")
    a("through Pisama's own product endpoints on a real n8n. **The funnel is the")
    a("claim** — every drop-off is itemized. Numbers below are copy-paste")
    a(f"reproducible from `{Path(args.results).name}` +")
    a("`eval/baseline_guard_campaign.json`.")
    a("")
    a("## The funnel")
    a("")
    a("| Stage | Count |")
    a("|---|---|")
    a(f"| Corpus workflows (committed) | {len(rows)} |")
    not_imported = (stages.get("error", 0) + stages.get("import_failed", 0)
                    + stages.get("no_execution_appeared", 0))
    a(f"| Imported + activated + produced a real execution | "
      f"{len(rows) - not_imported} |")
    with_failure = len(rows) - not_imported - stages.get("excluded", 0)
    a(f"| Real failure observed + detected | {with_failure} |")
    a(f"| Guard applied to the live workflow | {len(applied)} |")
    a(f"| Verified by real probe(s) | {len(probed)} |")
    a(f"| — of which standing guards (no succeeding payload exists; case honestly "
      f"stays observing) | {len(standing)} |")
    a(f"| Reached the FULL evidence bar (30 distinct successes + probes + zero "
      f"recurrence) — ready for human review | {len(ready)} |")
    a("| Concluded prevented by a script | 0 — never (human-only conclusions) |")
    a("")
    a("### Drop-off reasons")
    a("")
    for reason, count in sorted(excl.items(), key=lambda kv: -kv[1]):
        a(f"- excluded: {reason} — {count}")
    for stage in ("error", "import_failed", "no_execution_appeared",
                  "route_not_delivered",
                  "route_provenance_mismatch", "propose_failed", "target_failed",
                  "apply_failed", "destination_failed"):
        if stages.get(stage):
            a(f"- {stage} — {stages[stage]}")
    a("")
    a("### Lanes")
    a("")
    for lane, count in sorted(lanes.items()):
        a(f"- {lane}: {count}")
    a("")
    a(f"Executions fired: **{summary.get('executions_fired', '?')}** (all real n8n")
    a("runs; per-fire sync keeps every one inside the ingestion window).")
    a("")
    a("## The central finding (why zero cases reached the full bar)")
    a("")
    a("Under webhook re-hosting, the corpus splits almost perfectly into workflows")
    a("that ALWAYS succeed on constructible input (48 — no failure to guard) and")
    a("workflows that NEVER succeed on constructible input (the 17 guarded ones —")
    a("their code reads paths a webhook wrapper cannot satisfy). The intersection a")
    a("FULL verification needs — fails on one input, succeeds on another — is empty")
    a("in this corpus. That is a property of credential-free tutorial workflows")
    a("authored for empty manual input, not of the guard machinery: the n=1 dogfood")
    a("workflow (purpose-built with a real input contract) passes the full bar on")
    a("the live instance. Consequence: the live subset ships STANDING GUARDS")
    a("(durable controls with delivered-route probes), and the corpus adds no new")
    a("'prevented' conclusions. We say this rather than lowering the bar.")
    a("")
    a(DISCLOSURES)
    a("## Provenance")
    a("")
    env = summary.get("environment", {})
    a(f"- repo commit: `{corpus_sha}`")
    a(f"- server build_revision: `{env.get('server_build_revision')}`")
    a(f"- n8n host: `{env.get('n8n_url_host')}` (throwaway local stack for the "
      "full corpus; see scripts/run_corpus_campaign_local.sh)")
    a(f"- tier: `{env.get('tier')}`")
    a(f"- invocation: `{env.get('invocation')}`")
    a("")
    a("## Per-workflow appendix")
    a("")
    a("| id | lane | stage | probes | note |")
    a("|---|---|---|---|---|")
    for r in sorted(rows, key=lambda x: x["id"]):
        probes = []
        if r.get("probe_malformed"):
            probes.append("malformed✓")
        if r.get("probe_valid"):
            probes.append("valid✓")
        if r.get("probe_route"):
            probes.append("route✓")
        note = r.get("lane_reason") or r.get("successes_note") or \
            r.get("detail") or ""
        a(f"| {r['id']} | {r.get('lane')} | {r.get('stage')} | "
          f"{' '.join(probes) or '—'} | {str(note)[:80]} |")
    a("")

    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    return_code = main()
    raise SystemExit(return_code)
